<?xml version="1.0" encoding="utf-8"?><Database Name="mvc5" Class="dynamic_pageDataContext" xmlns="http://schemas.microsoft.com/linqtosql/dbml/2007">
  <Connection Mode="WebSettings" ConnectionString="Data Source=RAVEN\SQLEXPRESS;Initial Catalog=mvc5;Integrated Security=True" SettingsObjectName="System.Configuration.ConfigurationManager.ConnectionStrings" SettingsPropertyName="mvc5ConnectionString" Provider="System.Data.SqlClient" />
  <Table Name="dbo.dynamic_page" Member="dynamic_page">
    <Type Name="dynamic_page">
      <Column Name="id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="alias" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="title" Type="System.String" DbType="NVarChar(120) NOT NULL" CanBeNull="false" />
      <Column Name="content" Type="System.String" DbType="Text NOT NULL" CanBeNull="false" UpdateCheck="Never" />
      <Column Name="parent_id" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="create_date" Type="System.DateTime" DbType="Date NOT NULL" CanBeNull="false" />
      <Column Name="visible" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Column Name="deleted" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
    </Type>
  </Table>
</Database>